// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VueWithASP.Server.Models;

public partial class Company
{
    public int CompanyId { get; set; }

    public string ExportDate { get; set; }

    public string DataMonth { get; set; }

    public string CompanyCode { get; set; }

    public string CompanyName { get; set; }

    public string IndustryCategory { get; set; }

    public int? RevenueCurrentMonth { get; set; }

    public int? RevenueLastMonth { get; set; }

    public int? RevenueSameMonthLastYear { get; set; }

    public double? RevenueChangeLastMonthPercent { get; set; }

    public double? RevenueChangeSameMonthLastYearPercent { get; set; }

    public long? AccumulatedRevenueCurrentMonth { get; set; }

    public long? AccumulatedRevenueLastYear { get; set; }

    public double? AccumulatedRevenueChangePercent { get; set; }

    public string Remarks { get; set; }
}