// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using VueWithASP.Server.Models;

namespace VueWithASP.Server.Models
{
    public partial interface IprovisionContextProcedures
    {
        Task<int> SP_COMPANY_INSERTAsync(string EXPORT_DATE, string DATA_MONTH, string COMPANY_CODE, string COMPANY_NAME, string INDUSTRY_CATEGORY, int? REVENUE_CURRENT_MONTH, int? REVENUE_LAST_MONTH, int? REVENUE_SAME_MONTH_LAST_YEAR, double? REVENUE_CHANGE_LAST_MONTH_PERCENT, double? REVENUE_CHANGE_SAME_MONTH_LAST_YEAR_PERCENT, long? ACCUMULATED_REVENUE_CURRENT_MONTH, long? ACCUMULATED_REVENUE_LAST_YEAR, double? ACCUMULATED_REVENUE_CHANGE_PERCENT, string REMARKS, OutputParameter<string> O_MESSAGE, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_COMPANY_SELECTResult>> SP_COMPANY_SELECTAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
