// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace VueWithASP.Server.Models;

public partial class provisionContext : DbContext
{
    public provisionContext(DbContextOptions<provisionContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Company> Companies { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Company>(entity =>
        {
            entity.ToTable("COMPANY");

            entity.Property(e => e.CompanyId).HasColumnName("COMPANY_ID");
            entity.Property(e => e.AccumulatedRevenueChangePercent).HasColumnName("ACCUMULATED_REVENUE_CHANGE_PERCENT");
            entity.Property(e => e.AccumulatedRevenueCurrentMonth).HasColumnName("ACCUMULATED_REVENUE_CURRENT_MONTH");
            entity.Property(e => e.AccumulatedRevenueLastYear).HasColumnName("ACCUMULATED_REVENUE_LAST_YEAR");
            entity.Property(e => e.CompanyCode)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("COMPANY_CODE");
            entity.Property(e => e.CompanyName)
                .HasMaxLength(50)
                .HasColumnName("COMPANY_NAME");
            entity.Property(e => e.DataMonth)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("DATA_MONTH");
            entity.Property(e => e.ExportDate)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("EXPORT_DATE");
            entity.Property(e => e.IndustryCategory)
                .HasMaxLength(50)
                .HasColumnName("INDUSTRY_CATEGORY");
            entity.Property(e => e.Remarks)
                .HasMaxLength(100)
                .HasColumnName("REMARKS");
            entity.Property(e => e.RevenueChangeLastMonthPercent).HasColumnName("REVENUE_CHANGE_LAST_MONTH_PERCENT");
            entity.Property(e => e.RevenueChangeSameMonthLastYearPercent).HasColumnName("REVENUE_CHANGE_SAME_MONTH_LAST_YEAR_PERCENT");
            entity.Property(e => e.RevenueCurrentMonth).HasColumnName("REVENUE_CURRENT_MONTH");
            entity.Property(e => e.RevenueLastMonth).HasColumnName("REVENUE_LAST_MONTH");
            entity.Property(e => e.RevenueSameMonthLastYear).HasColumnName("REVENUE_SAME_MONTH_LAST_YEAR");
        });

        OnModelCreatingGeneratedProcedures(modelBuilder);
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}