// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace VueWithASP.Server.Models
{
    public partial class SP_COMPANY_SELECTResult
    {
        public int COMPANY_ID { get; set; }
        public string EXPORT_DATE { get; set; }
        public string DATA_MONTH { get; set; }
        public string COMPANY_CODE { get; set; }
        public string COMPANY_NAME { get; set; }
        public string INDUSTRY_CATEGORY { get; set; }
        public int? REVENUE_CURRENT_MONTH { get; set; }
        public int? REVENUE_LAST_MONTH { get; set; }
        public int? REVENUE_SAME_MONTH_LAST_YEAR { get; set; }
        public double? REVENUE_CHANGE_LAST_MONTH_PERCENT { get; set; }
        public double? REVENUE_CHANGE_SAME_MONTH_LAST_YEAR_PERCENT { get; set; }
        public long? ACCUMULATED_REVENUE_CURRENT_MONTH { get; set; }
        public long? ACCUMULATED_REVENUE_LAST_YEAR { get; set; }
        public double? ACCUMULATED_REVENUE_CHANGE_PERCENT { get; set; }
        public string REMARKS { get; set; }
    }
}
